/*******************************************************************************
 * Copyright (c) 2010,2022 IBM Corporation.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Dimitar Giormov - initial API and implementation
 *    IBM Corporation - documentation and tidy up
 *******************************************************************************/
/**
 * These are queries for snapshots generated by JRuby applications. 
 * The queries delivered with Memory Analyzer and their
 * expected parameters are not part of the API. Both names/identifiers and parameters may change.
 * Subject to that caveat, {@link org.eclipse.mat.snapshot.registry.RequestDetailResolverRegistry} can be used to call these queries.
*/
package org.eclipse.mat.jruby.resolver;
