/* Generated By:JavaCC: Do not edit this line. OQLParserConstants.java */
package org.eclipse.mat.parser.internal.oql.parser;

public interface OQLParserConstants
{

    int EOF = 0;
    int SINGLE_LINE_COMMENT = 9;
    int FORMAL_COMMENT = 10;
    int MULTI_LINE_COMMENT = 11;
    int K_AS = 13;
    int K_AS_RETAINED_SET = 14;
    int K_CALL = 15;
    int K_DISTINCT = 16;
    int K_IN = 17;
    int K_INSTANCEOF = 18;
    int K_IS = 19;
    int K_LIKE = 20;
    int K_NOT = 21;
    int K_OBJECTS = 22;
    int K_FROM = 23;
    int K_SELECT = 24;
    int K_UNION = 25;
    int K_WHERE = 26;
    int INTEGER_LITERAL = 27;
    int LONG_LITERAL = 28;
    int DECIMAL_LITERAL = 29;
    int HEX_LITERAL = 30;
    int OCTAL_LITERAL = 31;
    int FLOATING_POINT_LITERAL = 32;
    int EXPONENT = 33;
    int CHARACTER_LITERAL = 34;
    int STRING_LITERAL = 35;
    int TRUE = 36;
    int FALSE = 37;
    int OR = 38;
    int AND = 39;
    int NULL = 40;
    int IMPLEMENTS = 41;
    int DOLLAR_SIGN = 42;
    int IDENTIFIER = 43;
    int LETTER = 44;
    int DIGIT = 45;
    int LT = 46;
    int BANG = 47;
    int EQ = 48;
    int LE = 49;
    int GE = 50;
    int NE = 51;

    int DEFAULT = 0;
    int IN_SINGLE_LINE_COMMENT = 1;
    int IN_FORMAL_COMMENT = 2;
    int IN_MULTI_LINE_COMMENT = 3;

    String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\f\"", "\"//\"",
                    "<token of kind 7>", "\"/*\"", "<SINGLE_LINE_COMMENT>", "\"*/\"", "\"*/\"", "<token of kind 12>",
                    "\"AS\"", "\"AS RETAINED SET\"", "\"CALL\"", "\"DISTINCT\"", "\"IN\"", "\"INSTANCEOF\"", "\"IS\"",
                    "\"LIKE\"", "\"NOT\"", "\"OBJECTS\"", "\"FROM\"", "\"SELECT\"", "\"UNION\"", "\"WHERE\"",
                    "<INTEGER_LITERAL>", "<LONG_LITERAL>", "<DECIMAL_LITERAL>", "<HEX_LITERAL>", "<OCTAL_LITERAL>",
                    "<FLOATING_POINT_LITERAL>", "<EXPONENT>", "<CHARACTER_LITERAL>", "<STRING_LITERAL>", "\"true\"",
                    "\"false\"", "\"or\"", "\"and\"", "\"null\"", "\"implements\"", "\"$\"", "<IDENTIFIER>",
                    "<LETTER>", "<DIGIT>", "\"<\"", "\"!\"", "\"==\"", "\"<=\"", "\">=\"", "\"!=\"", "\";\"", "\"*\"",
                    "\",\"", "\".\"", "\"@\"", "\"(\"", "\")\"", "\"[]\"", "\"=\"", "\">\"", "\"+\"", "\"-\"", "\"/\"", };

}
