/* Generated By:JavaCC: Do not edit this line. OQLParserTokenManager.java */
package org.eclipse.mat.parser.internal.oql.parser;

public class OQLParserTokenManager implements OQLParserConstants
{
    public java.io.PrintStream debugStream = System.out;

    // $JL-SYS_OUT_ERR$

    public void setDebugStream(java.io.PrintStream ds)
    {
        debugStream = ds;
    }

    private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
    {
        switch (pos)
        {
            case 0:
                if ((active0 & 0x140L) != 0L || (active1 & 0x1L) != 0L)
                    return 2;
                if ((active0 & 0x80000000000000L) != 0L)
                    return 5;
                if ((active0 & 0x3f007ffe000L) != 0L)
                {
                    jjmatchedKind = 43;
                    return 17;
                }
                return -1;
            case 1:
                if ((active0 & 0x100L) != 0L)
                    return 0;
                if ((active0 & 0x3b007f18000L) != 0L)
                {
                    if (jjmatchedPos != 1)
                    {
                        jjmatchedKind = 43;
                        jjmatchedPos = 1;
                    }
                    return 17;
                }
                if ((active0 & 0x40000e6000L) != 0L)
                    return 17;
                return -1;
            case 2:
                if ((active0 & 0x33007d58000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 2;
                    return 17;
                }
                if ((active0 & 0x8000200000L) != 0L)
                    return 17;
                return -1;
            case 3:
                if ((active0 & 0x22007450000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 3;
                    return 17;
                }
                if ((active0 & 0x11000908000L) != 0L)
                    return 17;
                return -1;
            case 4:
                if ((active0 & 0x2006000000L) != 0L)
                    return 17;
                if ((active0 & 0x20001450000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 4;
                    return 17;
                }
                return -1;
            case 5:
                if ((active0 & 0x20000450000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 5;
                    return 17;
                }
                if ((active0 & 0x1000000L) != 0L)
                    return 17;
                return -1;
            case 6:
                if ((active0 & 0x20000050000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 6;
                    return 17;
                }
                if ((active0 & 0x400000L) != 0L)
                    return 17;
                return -1;
            case 7:
                if ((active0 & 0x10000L) != 0L)
                    return 17;
                if ((active0 & 0x20000040000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 7;
                    return 17;
                }
                return -1;
            case 8:
                if ((active0 & 0x20000040000L) != 0L)
                {
                    jjmatchedKind = 43;
                    jjmatchedPos = 8;
                    return 17;
                }
                return -1;
            case 9:
                if ((active0 & 0x20000040000L) != 0L)
                    return 17;
                return -1;
            default:
                return -1;
        }
    }

    private final int jjStartNfa_0(int pos, long active0, long active1)
    {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
    }

    private final int jjStopAtPos(int pos, int kind)
    {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private final int jjStartNfaWithStates_0(int pos, int kind, int state)
    {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }

    private final int jjMoveStringLiteralDfa0_0()
    {
        switch (curChar)
        {
            case 33:
                jjmatchedKind = 47;
                return jjMoveStringLiteralDfa1_0(0x8000000000000L);
            case 36:
                return jjStopAtPos(0, 42);
            case 40:
                return jjStopAtPos(0, 57);
            case 41:
                return jjStopAtPos(0, 58);
            case 42:
                return jjStopAtPos(0, 53);
            case 43:
                return jjStopAtPos(0, 62);
            case 44:
                return jjStopAtPos(0, 54);
            case 45:
                return jjStopAtPos(0, 63);
            case 46:
                return jjStartNfaWithStates_0(0, 55, 5);
            case 47:
                jjmatchedKind = 64;
                return jjMoveStringLiteralDfa1_0(0x140L);
            case 59:
                return jjStopAtPos(0, 52);
            case 60:
                jjmatchedKind = 46;
                return jjMoveStringLiteralDfa1_0(0x2000000000000L);
            case 61:
                jjmatchedKind = 60;
                return jjMoveStringLiteralDfa1_0(0x1000000000000L);
            case 62:
                jjmatchedKind = 61;
                return jjMoveStringLiteralDfa1_0(0x4000000000000L);
            case 64:
                return jjStopAtPos(0, 56);
            case 91:
                return jjMoveStringLiteralDfa1_0(0x800000000000000L);
            case 65:
            case 97:
                return jjMoveStringLiteralDfa1_0(0x8000006000L);
            case 67:
            case 99:
                return jjMoveStringLiteralDfa1_0(0x8000L);
            case 68:
            case 100:
                return jjMoveStringLiteralDfa1_0(0x10000L);
            case 70:
            case 102:
                return jjMoveStringLiteralDfa1_0(0x2000800000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa1_0(0x200000e0000L);
            case 76:
            case 108:
                return jjMoveStringLiteralDfa1_0(0x100000L);
            case 78:
            case 110:
                return jjMoveStringLiteralDfa1_0(0x10000200000L);
            case 79:
            case 111:
                return jjMoveStringLiteralDfa1_0(0x4000400000L);
            case 83:
            case 115:
                return jjMoveStringLiteralDfa1_0(0x1000000L);
            case 84:
            case 116:
                return jjMoveStringLiteralDfa1_0(0x1000000000L);
            case 85:
            case 117:
                return jjMoveStringLiteralDfa1_0(0x2000000L);
            case 87:
            case 119:
                return jjMoveStringLiteralDfa1_0(0x4000000L);
            default:
                return jjMoveNfa_0(3, 0);
        }
    }

    private final int jjMoveStringLiteralDfa1_0(long active0)
    {
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(0, active0, 0L);
            return 1;
        }
        switch (curChar)
        {
            case 42:
                if ((active0 & 0x100L) != 0L)
                    return jjStartNfaWithStates_0(1, 8, 0);
                break;
            case 47:
                if ((active0 & 0x40L) != 0L)
                    return jjStopAtPos(1, 6);
                break;
            case 61:
                if ((active0 & 0x1000000000000L) != 0L)
                    return jjStopAtPos(1, 48);
                else if ((active0 & 0x2000000000000L) != 0L)
                    return jjStopAtPos(1, 49);
                else if ((active0 & 0x4000000000000L) != 0L)
                    return jjStopAtPos(1, 50);
                else if ((active0 & 0x8000000000000L) != 0L)
                    return jjStopAtPos(1, 51);
                break;
            case 93:
                if ((active0 & 0x800000000000000L) != 0L)
                    return jjStopAtPos(1, 59);
                break;
            case 65:
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x2000008000L);
            case 66:
            case 98:
                return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
            case 69:
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
            case 72:
            case 104:
                return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa2_0(active0, 0x110000L);
            case 77:
            case 109:
                return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
            case 78:
            case 110:
                if ((active0 & 0x20000L) != 0L)
                {
                    jjmatchedKind = 17;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x8002040000L);
            case 79:
            case 111:
                return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
            case 82:
            case 114:
                if ((active0 & 0x4000000000L) != 0L)
                    return jjStartNfaWithStates_0(1, 38, 17);
                return jjMoveStringLiteralDfa2_0(active0, 0x1000800000L);
            case 83:
            case 115:
                if ((active0 & 0x2000L) != 0L)
                {
                    jjmatchedKind = 13;
                    jjmatchedPos = 1;
                }
                else if ((active0 & 0x80000L) != 0L)
                    return jjStartNfaWithStates_0(1, 19, 17);
                return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
            case 85:
            case 117:
                return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L);
            default:
                break;
        }
        return jjStartNfa_0(0, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(0, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(1, active0, 0L);
            return 2;
        }
        switch (curChar)
        {
            case 32:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
            case 68:
            case 100:
                if ((active0 & 0x8000000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 39, 17);
                break;
            case 69:
            case 101:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
            case 74:
            case 106:
                return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
            case 75:
            case 107:
                return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
            case 76:
            case 108:
                return jjMoveStringLiteralDfa3_0(active0, 0x12001008000L);
            case 79:
            case 111:
                return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
            case 80:
            case 112:
                return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
            case 83:
            case 115:
                return jjMoveStringLiteralDfa3_0(active0, 0x50000L);
            case 84:
            case 116:
                if ((active0 & 0x200000L) != 0L)
                    return jjStartNfaWithStates_0(2, 21, 17);
                break;
            case 85:
            case 117:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
            default:
                break;
        }
        return jjStartNfa_0(1, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(1, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(2, active0, 0L);
            return 3;
        }
        switch (curChar)
        {
            case 69:
            case 101:
                if ((active0 & 0x100000L) != 0L)
                    return jjStartNfaWithStates_0(3, 20, 17);
                else if ((active0 & 0x1000000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 36, 17);
                return jjMoveStringLiteralDfa4_0(active0, 0x1400000L);
            case 76:
            case 108:
                if ((active0 & 0x8000L) != 0L)
                    return jjStartNfaWithStates_0(3, 15, 17);
                else if ((active0 & 0x10000000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 40, 17);
                return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
            case 77:
            case 109:
                if ((active0 & 0x800000L) != 0L)
                    return jjStartNfaWithStates_0(3, 23, 17);
                break;
            case 79:
            case 111:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
            case 82:
            case 114:
                return jjMoveStringLiteralDfa4_0(active0, 0x4004000L);
            case 83:
            case 115:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
            case 84:
            case 116:
                return jjMoveStringLiteralDfa4_0(active0, 0x50000L);
            default:
                break;
        }
        return jjStartNfa_0(2, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(2, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(3, active0, 0L);
            return 4;
        }
        switch (curChar)
        {
            case 65:
            case 97:
                return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
            case 67:
            case 99:
                return jjMoveStringLiteralDfa5_0(active0, 0x1400000L);
            case 69:
            case 101:
                if ((active0 & 0x4000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 26, 17);
                else if ((active0 & 0x2000000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 37, 17);
                return jjMoveStringLiteralDfa5_0(active0, 0x20000004000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
            case 78:
            case 110:
                if ((active0 & 0x2000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 25, 17);
                break;
            default:
                break;
        }
        return jjStartNfa_0(3, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(3, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(4, active0, 0L);
            return 5;
        }
        switch (curChar)
        {
            case 77:
            case 109:
                return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
            case 78:
            case 110:
                return jjMoveStringLiteralDfa6_0(active0, 0x50000L);
            case 84:
            case 116:
                if ((active0 & 0x1000000L) != 0L)
                    return jjStartNfaWithStates_0(5, 24, 17);
                return jjMoveStringLiteralDfa6_0(active0, 0x404000L);
            default:
                break;
        }
        return jjStartNfa_0(4, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(4, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(5, active0, 0L);
            return 6;
        }
        switch (curChar)
        {
            case 65:
            case 97:
                return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
            case 67:
            case 99:
                return jjMoveStringLiteralDfa7_0(active0, 0x50000L);
            case 69:
            case 101:
                return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
            case 83:
            case 115:
                if ((active0 & 0x400000L) != 0L)
                    return jjStartNfaWithStates_0(6, 22, 17);
                break;
            default:
                break;
        }
        return jjStartNfa_0(5, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(5, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(6, active0, 0L);
            return 7;
        }
        switch (curChar)
        {
            case 69:
            case 101:
                return jjMoveStringLiteralDfa8_0(active0, 0x40000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
            case 78:
            case 110:
                return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
            case 84:
            case 116:
                if ((active0 & 0x10000L) != 0L)
                    return jjStartNfaWithStates_0(7, 16, 17);
                break;
            default:
                break;
        }
        return jjStartNfa_0(6, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(6, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(7, active0, 0L);
            return 8;
        }
        switch (curChar)
        {
            case 78:
            case 110:
                return jjMoveStringLiteralDfa9_0(active0, 0x4000L);
            case 79:
            case 111:
                return jjMoveStringLiteralDfa9_0(active0, 0x40000L);
            case 84:
            case 116:
                return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
            default:
                break;
        }
        return jjStartNfa_0(7, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(7, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(8, active0, 0L);
            return 9;
        }
        switch (curChar)
        {
            case 69:
            case 101:
                return jjMoveStringLiteralDfa10_0(active0, 0x4000L);
            case 70:
            case 102:
                if ((active0 & 0x40000L) != 0L)
                    return jjStartNfaWithStates_0(9, 18, 17);
                break;
            case 83:
            case 115:
                if ((active0 & 0x20000000000L) != 0L)
                    return jjStartNfaWithStates_0(9, 41, 17);
                break;
            default:
                break;
        }
        return jjStartNfa_0(8, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(8, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(9, active0, 0L);
            return 10;
        }
        switch (curChar)
        {
            case 68:
            case 100:
                return jjMoveStringLiteralDfa11_0(active0, 0x4000L);
            default:
                break;
        }
        return jjStartNfa_0(9, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa11_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(9, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(10, active0, 0L);
            return 11;
        }
        switch (curChar)
        {
            case 32:
                return jjMoveStringLiteralDfa12_0(active0, 0x4000L);
            default:
                break;
        }
        return jjStartNfa_0(10, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa12_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(10, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(11, active0, 0L);
            return 12;
        }
        switch (curChar)
        {
            case 83:
            case 115:
                return jjMoveStringLiteralDfa13_0(active0, 0x4000L);
            default:
                break;
        }
        return jjStartNfa_0(11, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa13_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(11, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(12, active0, 0L);
            return 13;
        }
        switch (curChar)
        {
            case 69:
            case 101:
                return jjMoveStringLiteralDfa14_0(active0, 0x4000L);
            default:
                break;
        }
        return jjStartNfa_0(12, active0, 0L);
    }

    private final int jjMoveStringLiteralDfa14_0(long old0, long active0)
    {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(12, old0, 0L);
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            jjStopStringLiteralDfa_0(13, active0, 0L);
            return 14;
        }
        switch (curChar)
        {
            case 84:
            case 116:
                if ((active0 & 0x4000L) != 0L)
                    return jjStopAtPos(14, 14);
                break;
            default:
                break;
        }
        return jjStartNfa_0(13, active0, 0L);
    }

    private final void jjCheckNAdd(int state)
    {
        if (jjrounds[state] != jjround)
        {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private final void jjAddStates(int start, int end)
    {
        do
        {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        }
        while (start++ != end);
    }

    private final void jjCheckNAddTwoStates(int state1, int state2)
    {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private final void jjCheckNAddStates(int start, int end)
    {
        do
        {
            jjCheckNAdd(jjnextStates[start]);
        }
        while (start++ != end);
    }

    @SuppressWarnings("unused")
    private final void jjCheckNAddStates(int start)
    {
        jjCheckNAdd(jjnextStates[start]);
        jjCheckNAdd(jjnextStates[start + 1]);
    }

    static final long[] jjbitVec0 = { 0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL };
    static final long[] jjbitVec1 = { 0x1ff00000fffffffeL, 0xffffffffffffc000L, 0xffffffffL, 0x600000000000000L };
    static final long[] jjbitVec3 = { 0x0L, 0x0L, 0x0L, 0xff7fffffff7fffffL };
    static final long[] jjbitVec4 = { 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL };
    static final long[] jjbitVec5 = { 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffL, 0x0L };
    static final long[] jjbitVec6 = { 0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L };
    static final long[] jjbitVec7 = { 0x3fffffffffffL, 0x0L, 0x0L, 0x0L };

    @SuppressWarnings("unused")
    private final int jjMoveNfa_0(int startState, int curPos)
    {
        int[] nextStates;
        int startsAt = 0;
        jjnewStateCnt = 42;
        int i = 1;
        jjstateSet[0] = startState;
        int j, kind = 0x7fffffff;
        for (;;)
        {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64)
            {
                long l = 1L << curChar;
                MatchLoop: do
                {
                    switch (jjstateSet[--i])
                    {
                        case 3:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(0, 6);
                            else if (curChar == 34)
                                jjCheckNAddTwoStates(14, 15);
                            else if (curChar == 39)
                                jjstateSet[jjnewStateCnt++] = 11;
                            else if (curChar == 46)
                                jjCheckNAdd(5);
                            else if (curChar == 47)
                                jjstateSet[jjnewStateCnt++] = 2;
                            if ((0x3fe000000000000L & l) != 0L)
                            {
                                if (kind > 27)
                                    kind = 27;
                                jjCheckNAddStates(7, 9);
                            }
                            else if (curChar == 48)
                            {
                                if (kind > 27)
                                    kind = 27;
                                jjCheckNAddStates(10, 13);
                            }
                            break;
                        case 0:
                            if (curChar == 42)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 1:
                            if ((0xffff7fffffffffffL & l) != 0L && kind > 7)
                                kind = 7;
                            break;
                        case 2:
                            if (curChar == 42)
                                jjstateSet[jjnewStateCnt++] = 0;
                            break;
                        case 4:
                            if (curChar == 46)
                                jjCheckNAdd(5);
                            break;
                        case 5:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 32)
                                kind = 32;
                            jjCheckNAddStates(14, 16);
                            break;
                        case 7:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(8);
                            break;
                        case 8:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 32)
                                kind = 32;
                            jjCheckNAddTwoStates(8, 9);
                            break;
                        case 10:
                            if (curChar == 39)
                                jjstateSet[jjnewStateCnt++] = 11;
                            break;
                        case 11:
                            if ((0xffffff7fffffdbffL & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 12;
                            break;
                        case 12:
                            if (curChar == 39 && kind > 34)
                                kind = 34;
                            break;
                        case 13:
                            if (curChar == 34)
                                jjCheckNAddTwoStates(14, 15);
                            break;
                        case 14:
                            if ((0xfffffffbffffdbffL & l) != 0L)
                                jjCheckNAddTwoStates(14, 15);
                            break;
                        case 15:
                            if (curChar == 34 && kind > 35)
                                kind = 35;
                            break;
                        case 17:
                            if ((0x3ff001000000000L & l) == 0L)
                                break;
                            if (kind > 43)
                                kind = 43;
                            jjstateSet[jjnewStateCnt++] = 17;
                            break;
                        case 18:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(0, 6);
                            break;
                        case 19:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(19, 20);
                            break;
                        case 20:
                            if (curChar != 46)
                                break;
                            if (kind > 32)
                                kind = 32;
                            jjCheckNAddStates(17, 19);
                            break;
                        case 21:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 32)
                                kind = 32;
                            jjCheckNAddStates(17, 19);
                            break;
                        case 23:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(24);
                            break;
                        case 24:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 32)
                                kind = 32;
                            jjCheckNAddTwoStates(24, 9);
                            break;
                        case 25:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(25, 26);
                            break;
                        case 27:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(28);
                            break;
                        case 28:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 32)
                                kind = 32;
                            jjCheckNAddTwoStates(28, 9);
                            break;
                        case 29:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(20, 22);
                            break;
                        case 31:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(32);
                            break;
                        case 32:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(32, 9);
                            break;
                        case 33:
                            if ((0x3fe000000000000L & l) == 0L)
                                break;
                            if (kind > 27)
                                kind = 27;
                            jjCheckNAddStates(7, 9);
                            break;
                        case 34:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 27)
                                kind = 27;
                            jjCheckNAdd(34);
                            break;
                        case 35:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(35, 36);
                            break;
                        case 37:
                            if (curChar != 48)
                                break;
                            if (kind > 27)
                                kind = 27;
                            jjCheckNAddStates(10, 13);
                            break;
                        case 38:
                            if ((0xff000000000000L & l) == 0L)
                                break;
                            if (kind > 27)
                                kind = 27;
                            jjCheckNAdd(38);
                            break;
                        case 39:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(39, 36);
                            break;
                        case 41:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 30)
                                kind = 30;
                            jjstateSet[jjnewStateCnt++] = 41;
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            else if (curChar < 128)
            {
                long l = 1L << (curChar & 077);
                MatchLoop: do
                {
                    switch (jjstateSet[--i])
                    {
                        case 3:
                        case 17:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 43)
                                kind = 43;
                            jjCheckNAdd(17);
                            break;
                        case 1:
                            if (kind > 7)
                                kind = 7;
                            break;
                        case 6:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(23, 24);
                            break;
                        case 9:
                            if ((0x5000000050L & l) != 0L && kind > 32)
                                kind = 32;
                            break;
                        case 11:
                            if ((0xffffffffefffffffL & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 12;
                            break;
                        case 14:
                            jjAddStates(25, 26);
                            break;
                        case 22:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(27, 28);
                            break;
                        case 26:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(29, 30);
                            break;
                        case 30:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(31, 32);
                            break;
                        case 36:
                            if ((0x100000001000L & l) != 0L && kind > 28)
                                kind = 28;
                            break;
                        case 40:
                            if ((0x100000001000000L & l) != 0L)
                                jjCheckNAdd(41);
                            break;
                        case 41:
                            if ((0x7e0000007eL & l) == 0L)
                                break;
                            if (kind > 30)
                                kind = 30;
                            jjCheckNAdd(41);
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            else
            {
                int hiByte = (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                MatchLoop: do
                {
                    switch (jjstateSet[--i])
                    {
                        case 3:
                        case 17:
                            if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 43)
                                kind = 43;
                            jjCheckNAdd(17);
                            break;
                        case 1:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 7)
                                kind = 7;
                            break;
                        case 11:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                                jjstateSet[jjnewStateCnt++] = 12;
                            break;
                        case 14:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                                jjAddStates(25, 26);
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            if (kind != 0x7fffffff)
            {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 42 - (jjnewStateCnt = startsAt)))
                return curPos;
            try
            {
                curChar = input_stream.readChar();
            }
            catch (java.io.IOException e)
            {
                return curPos;
            }
        }
    }

    private final int jjMoveStringLiteralDfa0_3()
    {
        switch (curChar)
        {
            case 42:
                return jjMoveStringLiteralDfa1_3(0x800L);
            default:
                return 1;
        }
    }

    private final int jjMoveStringLiteralDfa1_3(long active0)
    {
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            return 1;
        }
        switch (curChar)
        {
            case 47:
                if ((active0 & 0x800L) != 0L)
                    return jjStopAtPos(1, 11);
                break;
            default:
                return 2;
        }
        return 2;
    }

    private final int jjMoveStringLiteralDfa0_1()
    {
        return jjMoveNfa_1(0, 0);
    }

    @SuppressWarnings("unused")
    private final int jjMoveNfa_1(int startState, int curPos)
    {
        int[] nextStates;
        int startsAt = 0;
        jjnewStateCnt = 3;
        int i = 1;
        jjstateSet[0] = startState;
        int j, kind = 0x7fffffff;
        for (;;)
        {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64)
            {
                long l = 1L << curChar;
                MatchLoop: do
                {
                    switch (jjstateSet[--i])
                    {
                        case 0:
                            if ((0x2400L & l) != 0L)
                            {
                                if (kind > 9)
                                    kind = 9;
                            }
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 1:
                            if (curChar == 10 && kind > 9)
                                kind = 9;
                            break;
                        case 2:
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            else if (curChar < 128)
            {
                long l = 1L << (curChar & 077);
                MatchLoop: do
                {
                    switch (jjstateSet[--i])
                    {
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            else
            {
                int hiByte = (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                MatchLoop: do
                {
                    switch (jjstateSet[--i])
                    {
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            if (kind != 0x7fffffff)
            {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
                return curPos;
            try
            {
                curChar = input_stream.readChar();
            }
            catch (java.io.IOException e)
            {
                return curPos;
            }
        }
    }

    private final int jjMoveStringLiteralDfa0_2()
    {
        switch (curChar)
        {
            case 42:
                return jjMoveStringLiteralDfa1_2(0x400L);
            default:
                return 1;
        }
    }

    private final int jjMoveStringLiteralDfa1_2(long active0)
    {
        try
        {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e)
        {
            return 1;
        }
        switch (curChar)
        {
            case 47:
                if ((active0 & 0x400L) != 0L)
                    return jjStopAtPos(1, 10);
                break;
            default:
                return 2;
        }
        return 2;
    }

    static final int[] jjnextStates = { 19, 20, 25, 26, 29, 30, 9, 34, 35, 36, 38, 39, 36, 40, 5, 6, 9, 21, 22, 9, 29,
                    30, 9, 7, 8, 14, 15, 23, 24, 27, 28, 31, 32, };

    private static final boolean jjCanMove_0(int hiByte, @SuppressWarnings("unused") int i1, int i2,
                    @SuppressWarnings("unused") long l1, long l2)
    {
        switch (hiByte)
        {
            case 0:
                return ((jjbitVec0[i2] & l2) != 0L);
            default:
                return false;
        }
    }

    private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
    {
        switch (hiByte)
        {
            case 0:
                return ((jjbitVec3[i2] & l2) != 0L);
            case 48:
                return ((jjbitVec4[i2] & l2) != 0L);
            case 49:
                return ((jjbitVec5[i2] & l2) != 0L);
            case 51:
                return ((jjbitVec6[i2] & l2) != 0L);
            case 61:
                return ((jjbitVec7[i2] & l2) != 0L);
            default:
                if ((jjbitVec1[i1] & l1) != 0L)
                    return true;
                return false;
        }
    }

    public static final String[] jjstrLiteralImages = { "", null, null, null, null, null, null, null, null, null, null,
                    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "\44",
                    null, null, null, "\74", "\41", "\75\75", "\74\75", "\76\75", "\41\75", "\73", "\52", "\54", "\56",
                    "\100", "\50", "\51", "\133\135", "\75", "\76", "\53", "\55", "\57", };
    public static final String[] lexStateNames = { "DEFAULT", "IN_SINGLE_LINE_COMMENT", "IN_FORMAL_COMMENT",
                    "IN_MULTI_LINE_COMMENT", };
    public static final int[] jjnewLexState = { -1, -1, -1, -1, -1, -1, 1, 2, 3, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1,
                    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
                    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, };
    static final long[] jjtoToken = { 0xffffcffd5fffe001L, 0x1L, };
    static final long[] jjtoSkip = { 0xe3eL, 0x0L, };
    static final long[] jjtoSpecial = { 0xe00L, 0x0L, };
    static final long[] jjtoMore = { 0x11c0L, 0x0L, };
    protected SimpleCharStream input_stream;
    private final int[] jjrounds = new int[42];
    private final int[] jjstateSet = new int[84];
    StringBuffer image;
    int jjimageLen;
    int lengthOfMatch;
    protected char curChar;

    public OQLParserTokenManager(SimpleCharStream stream)
    {
        if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        input_stream = stream;
    }

    public OQLParserTokenManager(SimpleCharStream stream, int lexState)
    {
        this(stream);
        SwitchTo(lexState);
    }

    public void ReInit(SimpleCharStream stream)
    {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private final void ReInitRounds()
    {
        int i;
        jjround = 0x80000001;
        for (i = 42; i-- > 0;)
            jjrounds[i] = 0x80000000;
    }

    public void ReInit(SimpleCharStream stream, int lexState)
    {
        ReInit(stream);
        SwitchTo(lexState);
    }

    public void SwitchTo(int lexState)
    {
        if (lexState >= 4 || lexState < 0)
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
                            TokenMgrError.INVALID_LEXICAL_STATE);
        else
            curLexState = lexState;
    }

    protected Token jjFillToken()
    {
        Token t = Token.newToken(jjmatchedKind);
        t.kind = jjmatchedKind;
        String im = jjstrLiteralImages[jjmatchedKind];
        t.image = (im == null) ? input_stream.GetImage() : im;
        t.beginLine = input_stream.getBeginLine();
        t.beginColumn = input_stream.getBeginColumn();
        t.endLine = input_stream.getEndLine();
        t.endColumn = input_stream.getEndColumn();
        return t;
    }

    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    public Token getNextToken()
    {
        @SuppressWarnings("unused")
        int kind;
        Token specialToken = null;
        Token matchedToken;
        int curPos = 0;

        EOFLoop: for (;;)
        {
            try
            {
                curChar = input_stream.BeginToken();
            }
            catch (java.io.IOException e)
            {
                jjmatchedKind = 0;
                matchedToken = jjFillToken();
                matchedToken.specialToken = specialToken;
                return matchedToken;
            }
            image = null;
            jjimageLen = 0;

            for (;;)
            {
                switch (curLexState)
                {
                    case 0:
                        try
                        {
                            input_stream.backup(0);
                            while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
                                curChar = input_stream.BeginToken();
                        }
                        catch (java.io.IOException e1)
                        {
                            continue EOFLoop;
                        }
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_0();
                        break;
                    case 1:
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_1();
                        if (jjmatchedPos == 0 && jjmatchedKind > 12)
                        {
                            jjmatchedKind = 12;
                        }
                        break;
                    case 2:
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_2();
                        if (jjmatchedPos == 0 && jjmatchedKind > 12)
                        {
                            jjmatchedKind = 12;
                        }
                        break;
                    case 3:
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_3();
                        if (jjmatchedPos == 0 && jjmatchedKind > 12)
                        {
                            jjmatchedKind = 12;
                        }
                        break;
                }
                if (jjmatchedKind != 0x7fffffff)
                {
                    if (jjmatchedPos + 1 < curPos)
                        input_stream.backup(curPos - jjmatchedPos - 1);
                    if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
                    {
                        matchedToken = jjFillToken();
                        matchedToken.specialToken = specialToken;
                        if (jjnewLexState[jjmatchedKind] != -1)
                            curLexState = jjnewLexState[jjmatchedKind];
                        return matchedToken;
                    }
                    else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
                    {
                        if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
                        {
                            matchedToken = jjFillToken();
                            if (specialToken == null)
                                specialToken = matchedToken;
                            else
                            {
                                matchedToken.specialToken = specialToken;
                                specialToken = (specialToken.next = matchedToken);
                            }
                            SkipLexicalActions(matchedToken);
                        }
                        else
                            SkipLexicalActions(null);
                        if (jjnewLexState[jjmatchedKind] != -1)
                            curLexState = jjnewLexState[jjmatchedKind];
                        continue EOFLoop;
                    }
                    MoreLexicalActions();
                    if (jjnewLexState[jjmatchedKind] != -1)
                        curLexState = jjnewLexState[jjmatchedKind];
                    curPos = 0;
                    jjmatchedKind = 0x7fffffff;
                    try
                    {
                        curChar = input_stream.readChar();
                        continue;
                    }
                    catch (java.io.IOException e1)
                    {
                        // $JL-EXC$
                        // javacc generated code
                    }
                }
                int error_line = input_stream.getEndLine();
                int error_column = input_stream.getEndColumn();
                String error_after = null;
                boolean EOFSeen = false;
                try
                {
                    input_stream.readChar();
                    input_stream.backup(1);
                }
                catch (java.io.IOException e1)
                {
                    EOFSeen = true;
                    error_after = curPos <= 1 ? "" : input_stream.GetImage();
                    if (curChar == '\n' || curChar == '\r')
                    {
                        error_line++;
                        error_column = 0;
                    }
                    else
                        error_column++;
                }
                if (!EOFSeen)
                {
                    input_stream.backup(1);
                    error_after = curPos <= 1 ? "" : input_stream.GetImage();
                }
                throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar,
                                TokenMgrError.LEXICAL_ERROR);
            }
        }
    }

    void SkipLexicalActions(@SuppressWarnings("unused") Token matchedToken)
    {
        switch (jjmatchedKind)
        {
            default:
                break;
        }
    }

    void MoreLexicalActions()
    {
        jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
        switch (jjmatchedKind)
        {
            case 7:
                if (image == null)
                    image = new StringBuffer();
                image.append(input_stream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                input_stream.backup(1);
                break;
            default:
                break;
        }
    }
}
